"""Public provider-free Agent Context Pack product."""

from .canonical import (
    agent_context_pack_digest,
    agent_context_pack_machine_object,
    canonical_agent_context_pack,
    finalize_agent_context_pack,
)
from .errors import (
    AgentContextCanonicalError,
    AgentContextError,
    AgentContextInvariantError,
    AgentContextRequestError,
    AgentContextResourceError,
    AgentContextSourceError,
    AgentContextSourceUnavailableError,
    AgentContextSourceUnsupportedError,
    AgentContextUnavailableError,
    ContextProjectionContinuationMismatchError,
    ContextProjectionError,
    ContextProjectionResourceError,
    ContextProjectionUnsupportedProfileError,
)
from .context_projection import (
    CONTEXT_PROJECTION_ALGORITHM,
    CONTEXT_PROJECTION_ALGORITHM_VERSION,
    CONTEXT_PROJECTION_DIGEST_DOMAIN,
    CONTEXT_PROJECTION_SCHEMA_NAME,
    CONTEXT_PROJECTION_SCHEMA_VERSION,
    MAX_CONTEXT_PROJECTION_BYTES,
    MAX_CONTEXT_PROJECTION_LIMIT,
    ContextProjectionProfile,
    ContextProjectionRequest,
    build_context_projection,
)
from .models import (
    AGENT_CONTEXT_PACK_DIGEST_DOMAIN,
    AGENT_CONTEXT_PACK_SCHEMA_NAME,
    AGENT_CONTEXT_PACK_SCHEMA_VERSION,
    MAX_AGENT_CONTEXT_INTENT_BYTES,
    MAX_AGENT_CONTEXT_PACK_BYTES,
    AgentContextIncludedCounts,
    AgentContextOmittedCount,
    AgentContextPack,
    AgentContextPackKind,
    AgentContextPackRequest,
    AgentContextPresentationStatus,
    AgentContextSourceProvenance,
    AgentContextValidationViolation,
)
from .service import prepare_agent_context
from .validation import validate_agent_context_pack


__all__ = [
    "AGENT_CONTEXT_PACK_DIGEST_DOMAIN",
    "AGENT_CONTEXT_PACK_SCHEMA_NAME",
    "AGENT_CONTEXT_PACK_SCHEMA_VERSION",
    "MAX_AGENT_CONTEXT_INTENT_BYTES",
    "MAX_AGENT_CONTEXT_PACK_BYTES",
    "AgentContextCanonicalError",
    "AgentContextError",
    "AgentContextIncludedCounts",
    "AgentContextInvariantError",
    "AgentContextOmittedCount",
    "AgentContextPack",
    "AgentContextPackKind",
    "AgentContextPackRequest",
    "AgentContextPresentationStatus",
    "AgentContextSourceProvenance",
    "AgentContextRequestError",
    "AgentContextResourceError",
    "AgentContextSourceError",
    "AgentContextSourceUnavailableError",
    "AgentContextSourceUnsupportedError",
    "AgentContextUnavailableError",
    "AgentContextValidationViolation",
    "CONTEXT_PROJECTION_ALGORITHM",
    "CONTEXT_PROJECTION_ALGORITHM_VERSION",
    "CONTEXT_PROJECTION_DIGEST_DOMAIN",
    "CONTEXT_PROJECTION_SCHEMA_NAME",
    "CONTEXT_PROJECTION_SCHEMA_VERSION",
    "MAX_CONTEXT_PROJECTION_BYTES",
    "MAX_CONTEXT_PROJECTION_LIMIT",
    "ContextProjectionContinuationMismatchError",
    "ContextProjectionError",
    "ContextProjectionProfile",
    "ContextProjectionRequest",
    "ContextProjectionResourceError",
    "ContextProjectionUnsupportedProfileError",
    "agent_context_pack_digest",
    "agent_context_pack_machine_object",
    "canonical_agent_context_pack",
    "finalize_agent_context_pack",
    "prepare_agent_context",
    "build_context_projection",
    "validate_agent_context_pack",
]
