"""Immutable Observation Projection v0 Foundation; no repository access."""

from .canonical import canonical_projection, finalize, machine_object, projection_digest
from .errors import ObservationProjectionCanonicalError, ObservationProjectionError, ObservationProjectionInvariantError, ObservationProjectionRequestError
from .models import (
    Accounting,
    AccountingDomain,
    BudgetValue,
    ChangeKindCount,
    ContentState,
    CoverageAvailability,
    DiagnosticBoundary,
    DiagnosticCount,
    DiagnosticState,
    EntryMetadataFacts,
    EntryObjectHintFacts,
    EntryPayloadFacts,
    EntrySizeFacts,
    EntrySizeState,
    EntrySourceSide,
    ExpansionDescriptor,
    ExplicitEntryAnchor,
    HierarchyItem,
    HierarchyPresentationState,
    ObjectKindCount,
    ObservationProjection,
    OverlayItem,
    OverlayKind,
    PairTrackingBody,
    PairTrackingGrowthHierarchyContext,
    PairTrackingGrowthHierarchyItem,
    PairTrackingRequest,
    PayloadFactState,
    PathGrowthMetrics,
    PhysicalKnowledgeState,
    ProjectionBudget,
    ProjectionMode,
    ProjectionPolicy,
    ProjectionPreDigest,
    ProjectionSourceIdentity,
    ProjectionSourceValidity,
    ResultKind,
    ResultLocalReference,
    ResultNamespace,
    SelectionReason,
    SnapshotDiagnosticBody,
    SnapshotDiagnosticRequest,
    SnapshotPairSourceIdentity,
    SnapshotSourceIdentity,
    SourcePlanItem,
    SourcePlanState,
    SourceResultIdentity,
    StructureMetrics,
    TrackingItem,
)
from .validation import normalize_reasons, normalize_request, validate_budget, validate_predigest
from .snapshot_diagnostic import build_snapshot_diagnostic_projection
from .pair_tracking import build_pair_tracking_projection

__all__ = [
    "Accounting", "AccountingDomain", "BudgetValue", "ChangeKindCount", "ContentState",
    "CoverageAvailability", "DiagnosticBoundary", "DiagnosticCount", "DiagnosticState",
    "EntryMetadataFacts", "EntryObjectHintFacts", "EntryPayloadFacts", "EntrySizeFacts",
    "EntrySizeState", "EntrySourceSide", "ExpansionDescriptor", "ExplicitEntryAnchor",
    "HierarchyItem", "HierarchyPresentationState", "ObjectKindCount", "ObservationProjection",
    "ObservationProjectionCanonicalError", "ObservationProjectionError",
    "ObservationProjectionInvariantError", "ObservationProjectionRequestError", "OverlayItem",
    "OverlayKind", "PairTrackingBody", "PairTrackingGrowthHierarchyContext",
    "PairTrackingGrowthHierarchyItem", "PairTrackingRequest", "PayloadFactState",
    "PathGrowthMetrics",
    "PhysicalKnowledgeState", "ProjectionBudget", "ProjectionMode", "ProjectionPolicy",
    "ProjectionPreDigest", "ProjectionSourceIdentity", "ProjectionSourceValidity", "ResultKind",
    "ResultLocalReference", "ResultNamespace", "SelectionReason", "SnapshotDiagnosticBody",
    "SnapshotDiagnosticRequest", "SnapshotPairSourceIdentity", "SnapshotSourceIdentity",
    "SourcePlanItem", "SourcePlanState", "SourceResultIdentity", "StructureMetrics",
    "TrackingItem", "canonical_projection", "finalize", "machine_object", "projection_digest",
    "normalize_reasons", "normalize_request", "validate_budget", "validate_predigest",
    "build_snapshot_diagnostic_projection",
    "build_pair_tracking_projection",
]
