"""Provider-neutral, non-persistent LLM Context Layer foundation."""

from .adapter import build_context_packet, render_context_packet, task_domain_for_projection
from .canonical import (
    canonical_packet,
    canonical_request_constraints,
    finalize_packet,
    packet_digest,
    packet_machine_object,
    request_constraints_digest,
    request_constraints_machine_object,
)
from .errors import (
    LLMContextCanonicalError,
    LLMContextError,
    LLMContextInvariantError,
    LLMContextRequestError,
    LLMModelCallError,
    LLMOutputParseError,
    LLMOutputValidationError,
    LLMUnsupportedTaskDomainError,
)
from .models import (
    CONTEXT_DIGEST_DOMAIN,
    CONTEXT_PROTOCOL_VERSION,
    REQUEST_CONSTRAINTS_DIGEST_DOMAIN,
    REQUEST_CONSTRAINTS_VERSION,
    ContextBudget,
    ContextGrowthHierarchy,
    ContextOmission,
    ContextOmissionCategory,
    ContextRequestScope,
    ContextSourceRepresentation,
    EvidenceReference,
    EvidenceReferenceKind,
    EvidenceReferenceUse,
    ExplorationCapabilityClass,
    ExplorationItem,
    HypothesisItem,
    InterpretationItem,
    InterpretationStatus,
    LLMContextPacket,
    LLMInterpretationResult,
    LLMModelRequest,
    LLMTaskDomain,
    LLMValidationResult,
    ModelCallable,
    ObservationItem,
    SandboxRunResult,
    SemanticClass,
    RequestConstraints,
    UserIntentContext,
    ValidationStatus,
    ValidationViolation,
)
from .parser import parse_interpretation_result
from .output_contract import (
    CANONICAL_OUTPUT_CONTRACT,
    OUTPUT_CONTRACT_DIGEST_DOMAIN,
    OUTPUT_CONTRACT_ID,
    OUTPUT_CONTRACT_VERSION,
    OutputContractStructuralError,
    assert_output_contract_parity,
    canonical_output_contract_manifest,
    output_contract_digest,
    output_contract_manifest,
    render_output_contract_manifest,
    validate_output_contract_structure,
)
from .runner import (
    build_model_request,
    build_model_request_from_context,
    build_request_constraints,
    parse_request_constraints,
    render_request_constraints,
    run_once,
    validate_model_request_contract,
)
from .validation import validate_context_packet, validate_interpretation_result, validate_request_constraints

__all__ = [
    "CONTEXT_DIGEST_DOMAIN", "CONTEXT_PROTOCOL_VERSION", "REQUEST_CONSTRAINTS_DIGEST_DOMAIN",
    "REQUEST_CONSTRAINTS_VERSION", "ContextBudget", "ContextGrowthHierarchy",
    "ContextOmission", "ContextOmissionCategory", "ContextRequestScope", "ContextSourceRepresentation",
    "EvidenceReference", "EvidenceReferenceKind", "EvidenceReferenceUse", "ExplorationCapabilityClass",
    "ExplorationItem", "HypothesisItem", "InterpretationItem", "InterpretationStatus", "LLMContextCanonicalError",
    "LLMContextError", "LLMContextInvariantError", "LLMContextPacket", "LLMContextRequestError",
    "LLMInterpretationResult", "LLMModelCallError", "LLMModelRequest", "LLMOutputParseError",
    "LLMOutputValidationError", "LLMTaskDomain", "LLMUnsupportedTaskDomainError", "LLMValidationResult",
    "ModelCallable", "ObservationItem", "RequestConstraints", "SandboxRunResult", "SemanticClass", "UserIntentContext",
    "ValidationStatus", "ValidationViolation", "build_context_packet", "build_model_request", "canonical_packet",
    "canonical_request_constraints", "finalize_packet", "packet_digest", "packet_machine_object",
    "parse_interpretation_result", "render_context_packet", "request_constraints_digest",
    "request_constraints_machine_object", "run_once", "task_domain_for_projection", "validate_context_packet",
    "validate_interpretation_result", "validate_request_constraints", "CANONICAL_OUTPUT_CONTRACT", "OUTPUT_CONTRACT_DIGEST_DOMAIN",
    "OUTPUT_CONTRACT_ID", "OUTPUT_CONTRACT_VERSION", "OutputContractStructuralError",
    "assert_output_contract_parity", "canonical_output_contract_manifest", "output_contract_digest",
    "output_contract_manifest", "render_output_contract_manifest", "validate_output_contract_structure",
    "build_model_request_from_context", "build_request_constraints", "parse_request_constraints",
    "render_request_constraints", "validate_model_request_contract",
]
